# theme: jekyll-theme-minimal
# remote_theme: poole/poole
# remote_theme: mmistakes/minimal-mistakes
remote_theme: LeNPaul/Millennial
# theme: minima
title: Herzlich Willkommen
description: Ein erster Versuch mit github Webpages... und mmistakes minimal-mistakes
